### ISSUE TITLE
Connect Account Page to database

### ISSUE THREAD

**Issue by jyuwang** [Sashimi-App/Sashimi#15]
## Task Description:
Connect account page to database

## Task Check-list:
- [ ] remove hardcoded data
- [ ] connect to firebase
- [ ] add error checking to json; Handle potential errors in the readJson method. Right now, if the JSON file can't be read or the data can't be decoded, the app will crash. It would be better to catch these errors and handle them gracefully.
- [ ] 

## Task Timeline:
- [ ] Date: Update

Comment any questions and tag reviewers.
